Opentek-Org/opentek

.github/pull_request_template.md
README.md

Here I've created a PR template for your repo.

Create PR Template

---

css/about.css
pages/about.html

 Contributors section bugs fix

---

README.md

Installation steps updated to have more specific details on configuring live server if VS CODE is used as an IDE
- N/A
- Change 1 - Added links from free code camp on how to setup live server in vscode in ReadMe.md installation steps
- Change 2 - Also added StackOverflow link on how to change port number to a specific one for setting up auth0 in local dev environment setup
- For the new contributors , who may be unaware about how to start up a local server while working with project , the proposed change may come handy

Updated Installation Steps - Live server

---

css/projects.css

styling project cards

---

README.md

- Add PWA Feature To README
- Add to Features Section
- Resolved

Added PWA Feature To README

---

index.html
pages/Error.html
pages/about.html
pages/event.html
pages/program.html
pages/projects.html
pages/tutorial.html

- https://github.com/Opentek-Org/opentek/issues/61
- Add github logo to footer for all pages

added github social media logo to the footer

---

data/projects.json

* Update projects.json
* updated projects.json
* removed error in projects.json
* Update projects.json
* prettier done
- Change 1
- Change 2

Added Some projects in Projects.json (#63)

---

index.html

Website was messed up to due a unresolved merge conflict
- Fixed merge conflict
- -
** Original Screenshot **  |  ** Updated Screenshot *
*

merge conflict solved

---

data/projects.json

#55 Add Active projects in Projects.json
Added _DevTernShip_ project

added project in  project.json

---

css/style.css
index.html

- Change 1
- Change 2
** Original Screenshot **  |
|  ** Updated Screenshot **

 [Mobile] Navbar Styling-[hamburger-to-cross]

---

css/style.css
index.html
pages/Error.html
pages/about.html
pages/event.html
pages/program.html
pages/projects.html
pages/tutorial.html

- #21 
- Use Underline effect on hover on links and fixed responsiveness for all screen sizes
- 

footer revamped

---

index.html
js/event.js
js/program.js
js/projects.js
pages/about.html

Ran prettier on index.html as well. Please view it.

📄 Fixed Grammar and tone of the Website

---

data/tutorial.json
index.html
pages/event.html
pages/program.html
pages/projects.html
pages/tutorial.html

- #113
- Added Two Tutorial
- Added Target Attribute to Link tag in the Projects, Events, Programs & the Tutorials Page.

Added Target Attribute to Link tag

---

ads.txt
pages/Error.html
pages/about.html
pages/event.html
pages/program.html
pages/projects.html
pages/tutorial.html

ads placed

---

css/style.css
index.html
js/auth0.js

-Show Login/Signup form when user clicks on Events/Programs
- Added Listener to Login
- If the user is not logged in and click the event/program button he will ask to log in if already login then desired task will happen
** ![image](https://user-images.githubusercontent.com/68160897/147155482-fb445e2d-93fd-44bf-84eb-2985a3f01b4e.png) **  |  ** ![image](https://user-images.githubusercontent.com/68160897/147155238-1980145d-501a-4a34-8ed0-d96153c935de.png) **

RESOLVED - Show Login/Signup form when user clicks on Events/Programs

---

js/event.js

- Fixes #116 
- Changed the dimensions of image
- N/A

fixed image size

---

index.html

- issue #131 
- Change 1
- Change 2

[DiscordLink-updated]

---

css/style.css

- #125
https://swati002.github.io/opentek/
- Removed texture line from header
** Original Screenshot ** ![image](https://user-images.githubusercontent.com/72129763/147858440-ef276ebe-b468-4823-a8ba-5518fbc9b186.png) |  ** Updated Screenshot **

updated style.css

---

js/custom.js

- #118
- https://jashwanth-k.github.io/opentek/
- changed animate duration value form 600 to 50

fixed Slow transition via navbar

---

README.md

Added Community Partners section with images

---

pages/about.html

Image issue in about us page fixed

---

data/program.json

Solves issue #145 
- I've added some more tracks of the open source programs.
- I've removed some of the programs which were inactive from more than 2 years.
- I've left those programs untouched whose dates have not been announced yet.

removed inactive programs and added some new ones

---

css/style.css
index.html

added left and right transitions in the feature section using javascript AOS library
A very simple few lines of code is added which is easily understandable

added transition effects in feature section

---

index.html

- Change 1
**Live Code: (BEFORE Modification)**
```
<body>
<div></div>
<div></div>
<nav></nav>
<section></section>
<section></section>
<section></section>
<div></div>
<footer></footer>
<section></section>
<script></script>
</body>
```
- Change 2
**Live Code:(AFTER Modification)**
```
<body>
<div></div>
<div></div>
<header>
<nav></nav>
</header>
<main>
<section></section>
<section></section>
<section></section>
</main>
<div></div>
<footer></footer>
<section></section>
<script></script>
</body>
```
1. Modified Semantic Errors in` index.html` File. Put `<nav></nav>` section in `<header></header>` section.
2. After that, respective order of 3 specific `<section></section>` Elements put inside the separate` <main></main>` section.
3. …

Fixed Minor Semantic Errors

---

data/projects.json

Close Issue #213 
-Added Seamless UI project under Web Development
-Added Spectrum UI project under App Development

added Seamless UI and Spectrum UI

---

data/projects.json
index.html

Close issue #214 
-Added the Projects to Navbar in Home page which redirects users to projects site

Added Projects to Navbar in Home

---

data/projects.json
js/projects.js

Refactor: restructure projects data

---

css/projects.css
data/projects.json
js/projects.js
pages/projects.html

fixes #252 
Provided better method for users to select filters.
By default all the projects will be visible to users, the users can select any filter by click on it.
Provided better styling to the filter buttons.
Default view when the user opens projects page 👇 
After selecting particular filter 👇

feature: provide better filter options

---

css/projects.css
js/projects.js

-  Divs of project section's web dev portion is of not proper height #255 
- Height divs are corrected
- Shape of link to repo button is improved
- N/A

Removing Bug from Projects Page

---

index.html
pages/Error.html
pages/about.html
pages/blog.html
pages/event.html
pages/program.html
pages/projects.html
pages/tutorial.html

Fix: remove target attribute from nav link

---

css/about.css
css/blogs.css
css/color-theams.css
css/projects.css
css/responsive.css
css/slick.css
css/style.css
index.html
js/color-theam.js
pages/Error.html
pages/about.html
pages/blog.html
pages/event.html
pages/program.html
pages/projects.html
pages/tutorial.html

- #258 
- Added Color Themes In the website So that User can Select theme according to his/her choice.
- Improve the UI of buttons in the About Part of home Page and add hover effects in button.
- Below is the Video of  Changes
https://github.com/Opentek-Org/opentek/assets/119161467/178c76c0-185e-4d06-b05b-5a7c5a1d261d
Original  Theme
Updated Themes
Color Theme 1:      
!Color Theme 2:
Color Theme 3:

 Added Color Theams and also improve the buttons in About part of home Page 

---

css/style.css

- Fixed the issue #286 
- Fixed The nav bar on all pages at the top
- No
original
updated

Fixed the navbar at the top

---

css/projects.css
js/projects.js

Closes #237 
- I have added feature of showing all project without selecting any particular domain.
- I have also change style of overview section in projects page which will look great according to style of website.

[Feature Added] Show projects without selecting domain

---

css/style.css

-  Different color after hover on logo was not present
- Different colors for different logos on hover
- Its working fine no issue
- close #302 
- [
] Tests

Update style.css for footer-social

---

css/projects.css
pages/projects.html

issue reference number #282 
I've removed the extra scroll 
https://github.com/Opentek-Org/opentek/assets/71914071/b6214b1c-94a3-408b-80bd-af2a70cca2f4
bar and now the scroll to top functionality is working in projects page.

 Removing scroll bar and activating scroll to top functionality

---

css/projects.css
js/projects.js

[# Related Issues
Project Card UI Improvement #292
Can you assign the following issue to me?
design changes of the project card 
:---------------
----------:|:-------------------------:
**![Screenshot 2023-06-19 003758](https://github.com/Opentek-Org/opentek/assets/93905743/25e79169-bcb7-4219-ac34-477b26b1e435) **  |  ** 
**
](font-weight: 500;)

Project Card UI Improvement

---

css/style.css

- #301 
- Discord link is not working before now its working

discord link is now clickable(Level1)

---

data/projects.json

Add more projects for other people to contribute #245
- Change 1
I have added a Project Foodies - The Food Hub

Added a Project Foodies - The Food Hub

---

chatBot/script.js
chatBot/style.css
index.html

Closes #373 
Hello @AnirudhPanda  ,
I have added Chat Bot using API of Chat GPT v3.5
It is working smoothly and answering all the questions.
1. Visit to this website - https://rapidapi.com/Glavier/api/chatgpt53
2. Subscribe the `API` // important step without this API will not work, also this API is free of cost.
3. See the right side of the page :-
4. Copy the API key and paste in the key in the chatbot/script.js
[opentek.webm](https://github.com/Opentek-Org/opentek/assets/121503426/80adfff8-7409-44e6-ae6d-d7028bcbd363)

Added `openAI-GPT` chat bot

---

js/custom.js

Closes #371 
Lazy loading feature has been added in the website.

[ADDED]: Lazy loading

---

data/projects.json
data/tutorial.json

Title: Fix JSON file syntax error in project.json and tutorial.js
#386
- Fixed JSON syntax error in `project.json`
- Fixed JSON syntax error in ` tutorial.json`
No additional information.
Please attach the relevant screenshots depicting the changes made to the JSON files, if applicable.

fix : json Syntax error ✔

---

data/projects.json

- issue #388 
- Added project details

 Add project: Chat App (Issue #388)

---

index.html
pages/Error.html
pages/about.html
pages/blog.html
pages/event.html
pages/program.html
pages/projects.html
pages/tutorial.html

This pull request adds a comprehensive Voice and Chat AI Assistant to our project, enhancing user experience by providing quick answers to frequently asked questions (FAQ), describing various projects, and enabling seamless navigation throughout the application.
Features and Enhancements:
1. FAQ Module: The AI Assistant is equipped with natural language processing capabilities to understand and answer common user queries related to our application, services, and policies.
3. Navigation Assistance: The AI Assistant can assist users in navigating through different sections of the application, helping them find specific features and content efficiently.
4. Multi-platform Support: The AI Assistant is designed to work on both voice-based interactions (e.g., voice commands) and chat-based …

Fully Functional Voice and Chat AI Assistant for FAQ, Project Descriptions, and Navigation

---

css/projects.css

Resolve issue #349 
- change font to Poppins to match the website theme
- add border to card divs
- align cards content to center for better UI
- align category option to center and sync with cards container

Enhance projects UI

---

css/style.css
index.html

close #398
Hi, I've fixed the footer text, please check

Correct Footer Text

---

data/projects.json

[Added] - AI Fusion

---

js/projects.js

issue #420 fixed
** ![image](https://github.com/Opentek-Org/opentek/assets/101447544/f51920eb-8bba-4524-b352-23a924840c13)**  |  ** ![image](https://github.com/Opentek-Org/opentek/assets/101447544/18e0b6a3-5b8a-457d-8588-b68cd54da2a6)*

Enhancement : Latest Project Display First

---

index.html
pages/Error.html
pages/blog.html
pages/event.html
pages/program.html
pages/projects.html
pages/tutorial.html

This pull request addresses two issues related to our web application: the incorrect positioning of the voice assistant widget and the unwanted automatic popup behavior upon webpage reload. This PR includes the necessary changes to fix these issues and improve the user experience.
#428
**Changes Made:**
1. Adjusted the CSS styling of the voice assistant widget to ensure proper positioning on the webpage. The widget is now aligned correctly and appears in the desired location.
2. Modified the JavaScript code responsible for the automatic popup behavior to disable it on webpage reload. Users will no longer experience unexpected popups when reloading the page.
**Testing Done:**
To validate the changes, the following testing steps were performed:
1. Loaded the web application in various …

fix : issue is solve

---

pages/projects.html
pages/tutorial.html

close issue -> #429 
updated in all pages
- [yes ] Tests
- [yes ] Translations
- [yes ] Documentations

footer is added

---

Dockerfile
README.md

#407 
I have added an docker file which sets up an Nginx server in a container, copies an index.html file and a static directory to serve as static assets, exposes port 80, and starts the Nginx server when the container is launched.

Docker file is added

---

data/tutorial.json

#437 **Add more video data**
closes #437

Add New Video Resources

---

data/projects.json

[Added] - Tic-Tac-Toe

---

css/style.css
data/projects.json

#409 
- Change 1 - Fixed navbar issue for all pages. Now, the navbar is visible above the banner for all pages and links also work as expected.

Fixed Navbar issue for all pages

---

css/style.css
index.html

#449 
- The footer's alignment is not proper for different screen sizes. (not responsive)
- I made it centrally aligned when the screen size dropped below a certain size (767 px)
:----

Updated Footer alignment

---

css/responsive.css
css/style.css

- #466 
- padding x of 1 rem to nav-bg class
- change setting the color to black 

Improved the setting icon of the navbar

---

pages/jobs.html

#464   
- Change 1
- Change 2
- [x ] Tests
- [x ] Translations
- [x ] Documentations
** Original Screenshot **  |  ![image](https://github.com/Opentek-Org/opentek/assets/114687502/e9581169-d4f9-406b-9524-8e816300171c)

updated footer

---

index.html

#479
This pull request addresses the size issues of the AI chatbot in OpenTek by making changes to the Alan AI settings and adjusting the position of the chatbot to improve its appearance and usability.  
1. Modified Alan AI Settings: Adjusted the configuration of Alan AI to better handle the chatbot's size and appearance on different screen resolutions and devices. This ensures that the chatbot is displayed correctly and consistently across various platforms.
2. Position Adjustment: Changed the bottom and left position of the chatbot to align it properly within the OpenTek web application. This eliminates any overlapping issues and improves the chatbot's overall visibility.

Fixing Size Issues of AI Chatbot in OpenTek

---

pages/jobs.html

closes #469 
home should be redirecting to home page

redirecting home fixed

---

css/projects.css
js/projects.js

close #487
Hi @AnirudhPanda, I've fixed the issue and Added a no data found card.
please consider merging the pull request

Add no projects available card

---

server/app.js
server/errors.js

This pull request implements error handling in the application by creating custom error classes in the errors.js file. These custom error classes provide more meaningful and specific error messages for different scenarios. The error classes are used in the app.js file to handle different types of errors that might occur during the server's operation.
Changes Made:
1. Created custom error classes in the `errors.js` file to handle specific error scenarios:
- `TestimonialNotFoundError`: Used when the requested testimonial is not found.
- `DuplicateTestimonialError`: Used when attempting to add a testimonial that already exists.
- `InternalServerError`: Used when an internal server error occurs.
2. Set appropriate error messages, names, and status codes for each custom error class.
Code …

Implemented Error handling

---

data/projects.json

Added Essentia: a skincare products website

---

.github/dependabot.yml

Closes #510 
- update `directory`
- add `commit-message`
- add `labels`  
Please add this label in the repository: `📦 dependencies`.
> It will be used when dependabot opens a PR to update dependencies

docs: update dependabot workflow

---

.github/ISSUE_TEMPLATE/Project.yml
.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Closes #509 
> Image
- I have also added a dropdown in `bug` template, to get the information about the browser in which bug was found.
- I have updated all the issue forms  
- Please add the following labels, otherwise it would not be added with the issues.
- `⭐ goal: addition` (It was already added in the issue form)
> Label
| ![image](https://github.com/Opentek-Org/opentek/assets/74038190/c23824b3-b8cd-42e5-8537-7654983929d5)  |  ![image](https://github.com/Opentek-Org/opentek/assets/74038190/da7ba67f-c895-4283-8ebe-a1c8f377aeec) |

docs: update issue forms with proper checklist

---

.eslintrc
.eslintrc.json
.husky/commit-msg
.husky/pre-commit
.prettierrc
commitlint.config.js
package-lock.json
package.json

#526  , #527  , #528 
1. ESLint Setup: ESLint has been integrated into the project, enabling static code analysis to identify and enforce coding patterns and potential errors. The ESLint configuration file has been added with a set of rules tailored to our coding guidelines.
2. Commitlint Configuration: Commitlint has been set up to ensure consistent and meaningful commit messages across the repository. Now, every commit message will be validated against the specified commit message convention.
3. Prettier Integration: Prettier has been added to the project, enabling automatic code formatting to maintain consistent code styles. The Prettier configuration has been tailored to suit our project's coding standards.

 Setup ESLint, Commitlint, and Prettier for Codebase 🚀

---

css/style.css

Removed the breaked img form Tutorial Cards

---

js/projects.js
pages/projects.html

- Replaced `console.log` messages with `toast` notifications from the `react-toastify` library.
- Modified the `handleShareClick` function to show a toast notification when the URL is copied to the clipboard.
- Updated the `handleSaveClick` function to display a toast notification when a project is successfully saved.

Replaced Alerts with Toast Notifications

---

css/style.css
js/tutorial.js
pages/tutorial.html

#531 **[Feat]: Video description uses space inefficiently **
closes #531
Added Read More functionality for tutorial videos description
https://github.com/Opentek-Org/opentek/assets/86224794/186e7acd-75ae-4dd4-8a97-6ab036febc5a

Read more Functionality

---

data/tutorial.json

Added two video under tutorial page 
:-> Google Summer of Code | All about GSOC | Step by Step Explanation | How to prepare for GSOC?
:-> 5 Github Hacks that you should know | for Coders
** Updated Screenshot **

Added two video under Tutorial page

---

index.html
pages/Error.html
pages/about.html
pages/blog.html
pages/event.html
pages/jobs.html
pages/program.html
pages/projects.html
pages/roadmap.html
pages/saved.html
pages/tutorial.html

- Fixes Issue No : #567  
-  `Added title, rel, aria-label attributes to All Social Links in 10 HTML Files of pages Section`
- `Added required ARIA Attributes to Form Section existed in index.html File`
- These above changes are helpful for Improving Readability, Clean Code and Main thing is to Improved SEO Optimization due to affect of ARIA Attributes and Other Valid Attributes
- Also, Better thing is to resolved Web Accessibility and Screen Readers problems in DOM with Using In-Built Assistive Technologies(AT)

fix: Updated Social Links related Bugs/Issues in Respective HTML Files and Added ARIA attributes to Form Section in index.html File

---

index.html
js/auth.js

#580 
**Description:**
This pull request addresses the issues related to login and logout functionality, as well as the incorrect placement of Firebase scripts. The provided fix ensures that users can now log in and log out successfully, and Firebase is properly initialized before any Firebase-related code is executed.
**Changes Made:**
1. Moved the Firebase scripts to the head section of the HTML file to ensure they are loaded before the custom script.
2. Ensured that Firebase is properly initialized using the provided `firebaseConfig` before calling any Firebase-related functions.
3. Fixed the login function to trigger the Google sign-in provider correctly, enabling successful authentication.
4. Adjusted the logout function to properly sign out the user and reload the page after logout. …

FIxed login,logout and firebase

---

data/projects.json

Related Issue #586 
Hello @AnirudhPanda ,
I have added the DSA Repo for the interview perp. and also it is very easy to understand if someone view  the DSA.

chore: Added DSA Repo for Preperation

---

css/job.css

resolved issue #499
- changed the text color, alignment, and buttons enhancements

updated the job portal

---

data/add.py

#605 
- To enhance portability and make the script more adaptable to different environments, consider implementing relative file paths. This change would allow the script to work regardless of the user's specific file structure and location.
- While script includes basic error handling, you can further improve it by catching more specific exceptions and providing informative error messages. This enhancement will help diagnose issues more effectively and provide users with better feedback when errors occur during JSON file reading or Firestore data insertion.
- [ x] Tests
- [ x] Translations
- [ x] Documentations
** Original Screenshot **  |  ** …

Request for Improving Firestore Data Insertion Script

---

css/bookmark.css
css/projects.css
js/projects.js
js/saved.js
pages/projects.html
pages/saved.html

#571 
Description:
This pull request introduces an engaging enhancement to the projects.html page by incorporating a 3D bookmark animation for each project. Additionally, in the "Saved Projects" section, the bookmark checkbox is now checked by default, offering a seamless and intuitive user experience.
**Changes Made:**
1. **3D Bookmark Animation:**
- Integrated a captivating 3D bookmark animation for each project listed on the projects.html page.
- Utilized CSS animations and transformations to bring a visually appealing touch to the user interface.
2. **Default Checked State for Saved Projects:**
- In the "Saved Projects" section, set the bookmark checkbox to be checked by default.
- Ensured that users immediately recognize the bookmarked state of these projects.
**Screenshots:** …

Add 3D Bookmark Animation to Projects Page and Default Checked State for Saved Projects

---

.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/other.yml
CONTRIBUTING.md

#596 , #601 
I have added Guideline in `Contribution.md` and added Two Issue Template in `.github/ISSUE_TEMPLATE`

feat: Issue Template and Guideline in Contribute.md ✨

---

js/roadmap.js

- closes #604 
- **Road map download button bug**
changed the deployed URL to make the button work

Download button bug
